[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "replace-me"
dynamic = ["version"]
requires-python = ">=3.14"

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
fallback_version = "0.0.0"

[tool.hatch.build.hooks.vcs]
version-file = "src/replace_me/_version.py"